---
title: "Informationen zum Projektbericht"
---

## Inhalt

Der Projektbericht soll pro Gruppenmitglied maximal 10 Seiten umfassen, wobei insgesamt etwa 10.000 Wörter (ca. 40 Seiten) als Richtwert gelten. Die Seitenanzahl ist jedoch lediglich eine Orientierung; im Vordergrund steht die Qualität der Ausarbeitung. Gute und präzise Projektberichte können teilweise auch nur 20-25 Seiten lang sein. Entscheidend ist eine fundierte Bearbeitung des Themas, eine sorgfältige Analyse der Daten sowie eine sachgerechte Einordnung der Ergebnisse. Wichtige Grafiken und Tabellen sollen in den Text integriert werden, während ergänzende Analysen im Anhang Platz finden. Die Hausarbeit soll die folgenden Bestandteile enthalten: Einleitung, Theorie-/Literaturteil, Methoden, Ergebnisse und Diskussion. Zudem ist die Dokumentation der eigenen Arbeit unerlässlich, wobei Sie selbstverständlich die im Verlauf des Semester angefertigte Dokumentation weiterverwerten können. Wichtig ist, dass es nicht zwingend "signifikante" Ergebnisse geben muss – der Lernprozess steht im Vordergrund. Die Einhaltung der Formalien und Regeln wissenschaftlicher Arbeit ist notenrelevant. Viele Inhalte und Anforderungen werden bereits im Verlauf des Semester in den Kleingruppen besprochen — bei Bedarf können jedoch auch Sprechstundentermine vereinbart werden, um konkrete Fragen zu besprechen.


Weitere Informationen zum konkreten Aufbau des Projekterichts erfolgen in der letzten Sitzung des Semesters. Außerdem finden Sie grundlegende Informationen auf den folgenden Seiten:

- <https://www.studium.ifp.uni-mainz.de/studierende/seminararbeiten/>
- <https://www.studium.ifp.uni-mainz.de/studierende/seminararbeiten/formale-vorgaben/>

Im Speziellen gelten die folgenden Anforderungen an den Projektbericht:

## Umfang

- maximal (!) 40 Seiten Text (10 Seiten pro Person), exkl. Deckblatt, Inhaltsverzeichnis, Literaturverzeichnis etc.

## Formatierung

- Schriftart: Times New Roman (Schriftgröße 12) oder Arial (Schriftgröße 11)
- 1,5-facher Zeilenabstand
- Blocksatz, blocksatzbedingte Leerstellen innerhalb der Zeilen sind durch automatische Silbentrennung zu vermeiden
- Seitenränder: Abstand zum Seitenrand je 2,5 cm nach oben und unten, 3,5 cm nach links und 3 cm nach rechts
- Zitation nach APA 7 (siehe [APA Website](https://www.apastyle.org)
  - Direkte und indirekte Zitate erfolgen ausschließlich als Kurzbelege nach APA (keine Fußnotenbelege)
  - Für das Anlegen einer Literaturliste nach APA hilfreich: Literatursoftware Citavi oder Zotero (per ZDV-Apps dem eigenen Uni-Account zuweisen)
  - Fußnoten in Schriftgröße 10 am jeweiligen Seitenende können sparsam für Ergänzungen und Hintergrundinformationen eingesetzt werden

## Plagiate

- Der Hausarbeit muss am Ende eine unterschriebene eidesstattliche Erklärung über das eigenständige Anfertigen der Arbeit beiliegen. Andernfalls kann die Arbeit nicht als Prüfungsleistung anerkannt werden.
- Um Plagiate zu vermeiden, belegen Sie alle (prinzipiell überprüfbaren) Tatsachenbehauptungen mit wissenschaftlicher Literatur. Weiterführende Interpretationen, Theorietransfer und eigene Gedanken bedürfen keines Belegs. Sie können und sollten diese Eigenleistungen jedoch mit Literatur und empirischen Befunden untermauern, die den jeweiligen Gedankengang unterstützen.
- Einsatz von "KI": In diesem Seminar ist der Einsatz von "KI"-Werkzeugen für unterstützende Aufgaben erlaubt, bspw. das Verstehen von Konzepten oder die Korrektur von Rechtschreibfehlern. Ebenso dürfen Sie sich bei der Arbeit mit Programmiersprachen wie R oder Python unterstützen lassen. Unzulässig ist jedoch die Nutzung von überwiegend "KI"-generiertem Text in Aufgaben ohne Quellenangabe oder die vollständige Bearbeitung von Arbeitsschritten durch "KI". Falls "KI"-Werkzeuge verwendet werden, muss dies transparent angegeben werden. Für die Richtigkeit der Ergebnisse sind Sie selbst verantwortlich!

## Abgabe des Projektberichts

- Frist: 01.09.2025, 12:00 Uhr (keine Verlängerung ohne Attest möglich)
- Abgabe einer elektronischen Version (PDF) über die Abgabefunktion im LMS ("Abgabe der Hausarbeit") — es genügt eine Abgabe pro Gruppe
- Ergänzende Materialien (Analyseskripte, Datensätze, etc.) als .zip-Datei verpacken und hochladen